import { Attribute, Vital, Skill, NumberIndexedDict } from "./types";

export const ATTRIBUTE_NAME = {
  [Attribute.strength]: "Strength",
  [Attribute.endurance]: "Endurance",
  [Attribute.coordination]: "Coordination",
  [Attribute.quickness]: "Quickness",
  [Attribute.focus]: "Focus",
  [Attribute.self]: "Self",
};

export const VITAL_FORMULA = {
  [Vital.health]: "E/2",
  [Vital.stamina]: "E",
  [Vital.mana]: "W",
};

export const SKILL_NAME = {
  [Skill.alchemy]: "Alchemy",
  [Skill.appraise]: "Appraise",
  [Skill.arcane_lore]: "Arcane Lore",
  [Skill.armor_tinkering]: "Armor Tinkering",
  [Skill.assess]: "Assess",
  [Skill.awareness]: "Awareness",
  [Skill.axe_and_mace]: "Axe and Mace",
  [Skill.bow_and_crossbow]: "Bow and Crossbow",
  [Skill.cooking]: "Cooking",
  [Skill.dagger]: "Dagger",
  [Skill.deception]: "Deception",
  [Skill.dual_wield]: "Dual Wield",
  [Skill.fletching]: "Fletching",
  [Skill.healing]: "Healing",
  [Skill.item_tinkering]: "Item Tinkering",
  [Skill.jump]: "Jump",
  [Skill.leadership]: "Leadership",
  [Skill.life_magic]: "Life Magic",
  [Skill.lockpick]: "Lockpick",
  [Skill.loyalty]: "Loyalty",
  [Skill.magic_defense]: "Magic Defense",
  [Skill.magic_item_tinkering]: "Magic Item Tinkering",
  [Skill.mana_conversion]: "Mana Conversion",
  [Skill.melee_defense]: "Melee Defense",
  [Skill.missile_defense]: "Missile Defense",
  [Skill.portal_magic]: "Portal Magic",
  [Skill.run]: "Run",
  [Skill.salvaging]: "Salvaging",
  [Skill.shield]: "Shield",
  [Skill.spear_and_staff]: "Spear and Staff",
  [Skill.stealth]: "Stealth",
  [Skill.sword]: "Sword",
  [Skill.thrown_weapons]: "Thrown Weapons",
  [Skill.two_handed_combat]: "Two-Handed Combat",
  [Skill.unarmed_combat]: "Unarmed Combat",
  [Skill.war_magic]: "War Magic",
  [Skill.weapon_tinkering]: "Weapon Tinkering",
};

export const SKILL_FORMULA = {
  [Skill.alchemy]: "(C+F)/4",
  [Skill.appraise]: "(C+F)/4",
  [Skill.arcane_lore]: "(F+W)/2",
  [Skill.armor_tinkering]: "(E+F)/2",
  [Skill.assess]: "F",
  [Skill.awareness]: "F/2",
  [Skill.axe_and_mace]: "S/2",
  [Skill.bow_and_crossbow]: "C/2",
  [Skill.cooking]: "(C+F)/4",
  [Skill.dagger]: "Q/2",
  [Skill.deception]: "W",
  [Skill.dual_wield]: "C/2",
  [Skill.fletching]: "(C+F)/4",
  [Skill.healing]: "(C+F)/3",
  [Skill.item_tinkering]: "F",
  [Skill.jump]: "(S+C)/4",
  [Skill.leadership]: "",
  [Skill.life_magic]: "F/2",
  [Skill.lockpick]: "(C+F)/2",
  [Skill.loyalty]: "",
  [Skill.magic_defense]: "(F+W)/4",
  [Skill.magic_item_tinkering]: "(F+W)/2",
  [Skill.mana_conversion]: "(F+W)/4",
  [Skill.melee_defense]: "(C+Q)/4",
  [Skill.missile_defense]: "(C+Q)/4",
  [Skill.portal_magic]: "",
  [Skill.run]: "Q/2",
  [Skill.salvaging]: "",
  [Skill.shield]: "(S+E)/2",
  [Skill.spear_and_staff]: "C/2",
  [Skill.stealth]: "(Q+F)/4",
  [Skill.sword]: "S/2",
  [Skill.thrown_weapons]: "S/2",
  [Skill.two_handed_combat]: "S/2",
  [Skill.unarmed_combat]: "C/2",
  [Skill.war_magic]: "W/2",
  [Skill.weapon_tinkering]: "(S+F)/2",
};

export const BUFF_NAME: NumberIndexedDict<string> = {
  0: "",
  1: "I",
  2: "II",
  3: "III",
  4: "IV",
  5: "V",
  6: "VI",
  7: "VII",
};

export const CANTRIP_NAME: NumberIndexedDict<string> = {
  0: "None",
  1: "Minor",
  2: "Major",
  3: "Epic",
  4: "Legen.",
};
